### PR TITLE
New Sqlite3 driver

### PR DESCRIPTION
**Pull request by maiste**
This PR introduces a driver for `Sqlite3`. It relies on `sqlite3-ocaml` to stay as low level as possible.

It requires #2 to be merged to support this new driver.

### CODE REVIEW

**Review by maiste — COMMENTED** [review]
Thanks for the formatting, I always forget to run `dune fmt` to format dune files as the code is autoformatted on my editor :sweat_smile:

**Comment by tmattio** [comment]
Thanks @maiste!

I tried to run the driver on example migrations (that I pushed to the `example/` directory) and I have the following error:

```
dune exec omigrate -- setup --source ./example --database sqlite3://./db.sqlite3
omigrate: internal error, uncaught exception:
          Sqlite3.Error("error opening database: unable to open database file")
```

Do you know what's going wrong?

**Comment by maiste** [comment]
I replicate the issue: it seems to struggle with relative path. If you put an absolute path, it will work. Investigate on a way to fix that.

**Comment by tmattio** [comment]
Thanks @maiste! Sorry for the noise, I thought it was supported, but if the RFC is explicit about not supporting it, we shouldn't either!

I still have an error running the migrations though. After cleaning the SQL bits from the migrations that are not supported by sqlite3, I have the following error:

```
dune exec omigrate -- setup -d "sqlite3://$PWD/my_db.db" -s "./example"
omigrate: internal error, uncaught exception:
          Sqlite3.Error("Sqlite3.prepare: near \"(\": syntax error")
```

**Comment by maiste** [comment]
I was pushing some code to update the codebase. The `README` is not supposed to be in the migration repository, which triggers the bug. To clarify the structure, I've split `example` into two subdirectories, `postgres` and `sqlite3`. This way, you can run the example with the following :
```
dune exec omigrate -- setup -d "sqlite3://$PWD/my_db.db" -s "./example/sqlite3"
```
As `postgres` and `sqlite3` doesn't support the same set of features, the `sqlite3` are the same as in `go-migrate`.

**Pull request merged**
